--What are the details of all cars purchased in 2022?
SELECT dc. car_id, ds.purchase_date ,dc.make,dc.type,dc.style,dc.cost_$
FROM [dbo].[sales] ds
join [dbo].[cars] dc on dc.car_id = ds.car_id
where Year ( purchase_date) ='2022'


 --What is the total number of cars sold by each sales person?
 SELECT sp.name, count(s.car_id) as [# cars sold]
 FROM[dbo].[sales] s
 Join [dbo].[salespersons] sp on s.salesman_id=sp.salesman_id
 Group by name
 
 
 --What is the total revenue generated by each sales person ?
 SELECT sp.name, sum (c.cost_$) as [total revenue] 
 FROM [dbo].[cars] c
 join[dbo].[sales] s on c.car_id= s.car_id
 join [dbo].[salespersons] sp on s.salesman_id =sp.salesman_id
 Group by name 

 --What are the details of the car sold by each sales person 
 SELECT sp.name,c.make,c.style,c.cost_$, s. purchase_date
 FROM [dbo].[sales] s
 join [dbo].[salespersons] sp on s.salesman_id =sp. salesman_id
 join [dbo].[cars] c on s.car_id =c.car_id
 
 --What is the total revenue generated by each car type?
 SELECT Type, sum(cost_$) as [total revenue]
 FROM [dbo].[cars]
 Group by type
 
 --What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
 SELECT sp.name, s.salesman_id,c.cost_$,c.type,c.make,c.style,s.purchase_date
 FROM [dbo].[sales] s
 JOIN [dbo].[salespersons] sp on s.salesman_id =sp.salesman_id
 join [dbo].[cars] c on c.car_id=s.car_id
 where YEAR(s.purchase_date)= 2021 and sp.name= 'Emily Wong'
 
 --What is the total revenue generated by the sales of hatchback cars?
 SELECT c. style, sum(c.cost_$) AS [Total revenue], count (s.car_id) AS [sales order]
 FROM [dbo].[cars] c
 join [dbo].[sales] s on c.car_id=s.car_id
 where style='Hatchback' 
 Group by style

 --What is the total revenue generated by the sales of SUV cars in the year 2022?
 SELECT c.style,  c.cost_$ , s.purchase_date
 FROM [dbo].[cars] c
 join [dbo].[sales] s on c.car_id=s.car_id
 where year (s.purchase_date)= 2022 and style='SUV'
 

 --What is the name and city of the salesperson who sold the most number of cars in the year 2023?
 SELECT sp.name, sum (s.car_id) as [# cars sold], sp.city
 FROM[dbo].[sales] s
 Join [dbo].[salespersons] sp on s.salesman_id=sp.salesman_id
 where (s.purchase_date) ='2023'
 Group by name, city
 order by [# cars sold]
 
 --What is the name and age of the salesperson who generated the highest revenue in the year 2022?
 SELECT sum (c.cost_$) As Highestrevenue, sp.name,sp.age, count(s.salesman_id)as[salesman]
 FROM [dbo].[salespersons] sp
 JOIN [dbo].[sales] s on sp.salesman_id =s.salesman_id
 join [dbo].[cars] c on s.car_id =c.car_id
 where year (s.purchase_date) ='2022' 
 group by name, age
 order by Highestrevenue  DESC
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 




 
 
 
 
 

 